### PR TITLE
Added a logo

### PR DESCRIPTION
**Pull request by J-tt**
Feel free to leave feedback, I'm pretty happy with it but I can change it around :smile:

### CODE REVIEW

**Comment by Heholord** [comment]
Oh wow, thank you!

**Comment by J-tt** [comment]
It was my pleasure :)
I really liked the project so thought I return something :smile:

**Comment by Heholord** [comment]
I named you in the README.md, hope you are okay with that :)

**Comment by J-tt** [comment]
That's awesome :grinning: thank you!

**Pull request merged**
